"""initial_schema

Revision ID: 9cc372a7cbb6
Revises: 
Create Date: 2026-06-28 09:10:35.296357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc372a7cbb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('undone', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_logs_batch'), 'deletion_logs', ['batch'], unique=False)
    op.create_index(op.f('ix_deletion_logs_id'), 'deletion_logs', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('preview_path', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('camera_make', sa.String(length=128), nullable=True),
    sa.Column('camera_model', sa.String(length=128), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('ai_tags', sa.Text(), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_screenshot', sa.Boolean(), nullable=False),
    sa.Column('is_dark', sa.Boolean(), nullable=False),
    sa.Column('is_overexposed', sa.Boolean(), nullable=False),
    sa.Column('is_low_res', sa.Boolean(), nullable=False),
    sa.Column('burst_id', sa.String(length=36), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_batch', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_photos_burst_id'), 'photos', ['burst_id'], unique=False)
    op.create_index(op.f('ix_photos_deleted_at'), 'photos', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_photos_deleted_batch'), 'photos', ['deleted_batch'], unique=False)
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    op.create_index(op.f('ix_photos_is_dark'), 'photos', ['is_dark'], unique=False)
    op.create_index(op.f('ix_photos_is_favorite'), 'photos', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_photos_is_low_res'), 'photos', ['is_low_res'], unique=False)
    op.create_index(op.f('ix_photos_is_overexposed'), 'photos', ['is_overexposed'], unique=False)
    op.create_index(op.f('ix_photos_is_screenshot'), 'photos', ['is_screenshot'], unique=False)
    op.create_index(op.f('ix_photos_perceptual_hash'), 'photos', ['perceptual_hash'], unique=False)
    op.create_index(op.f('ix_photos_taken_at'), 'photos', ['taken_at'], unique=False)
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_photo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cover_photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_id'), 'albums', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_table('photo_albums',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id', 'album_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_albums')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_albums_id'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('ix_photos_taken_at'), table_name='photos')
    op.drop_index(op.f('ix_photos_perceptual_hash'), table_name='photos')
    op.drop_index(op.f('ix_photos_is_screenshot'), table_name='photos')
    op.drop_index(op.f('ix_photos_is_overexposed'), table_name='photos')
    op.drop_index(op.f('ix_photos_is_low_res'), table_name='photos')
    op.drop_index(op.f('ix_photos_is_favorite'), table_name='photos')
    op.drop_index(op.f('ix_photos_is_dark'), table_name='photos')
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_deleted_batch'), table_name='photos')
    op.drop_index(op.f('ix_photos_deleted_at'), table_name='photos')
    op.drop_index(op.f('ix_photos_burst_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_deletion_logs_id'), table_name='deletion_logs')
    op.drop_index(op.f('ix_deletion_logs_batch'), table_name='deletion_logs')
    op.drop_table('deletion_logs')
    # ### end Alembic commands ###
